# Companion to plot_auc_summary.py: instead of one AUC per dataset (pooling
# every across-session unit-pair together regardless of how far apart the two
# sessions were recorded), bin across-session unit-pairs by delta-days
# (|date(RecSes A) - date(RecSes B)|) and compute AUC per bin per model,
# pooling across every dataset -- to see whether/how tracking quality decays
# as the gap between recordings grows.
#
# AUC_summary.json (produced once per dataset/model by
# run_deepunitmatch_batch_onMerged.py / run_emd_batch_onMerged.py /
# run_dant_batch_onMerged.py) only stores the whole-dataset scalar AUC, and
# recording dates are never persisted anywhere in BASE_OUTPUT -- the merged
# tree's numbered session folders (0, 1, 2, ...) don't carry dates, and even
# the non-merged root's per-session dates (recoverable from each group's
# UMparam.pickle KS_dirs, see generate_metadata_index.py) don't map directly
# onto a MatchTable.csv's "RecSes" numbers: sessions with zero good units (or
# whose good units all lost their RawSpikes file) are silently dropped when
# run_deepunitmatch_batch_onMerged.py's _prepare_session() builds session_id,
# renumbering RecSes to skip the gaps.
#
# Rather than persisting that mapping from a pipeline run (which would need
# re-running the batch scripts), this script reconstructs it from files that
# already sit statically in the merged tree: build_session_date_lookup()
# redoes exactly the good-unit/RawSpikes-exists bookkeeping _prepare_session()
# does (the same logic run_emd_batch_onMerged.py's --stage phase already uses
# to work out good units without touching waveform data) to recover, for each
# dataset, which original KS_dirs index survived as each RecSes number -- then
# looks up that index's date in metadata_index.json. This is read-only and
# doesn't require re-running any matching.
#
# Output (plots + CSVs) is written to BASE_OUTPUT/auc_vs_delta_days_report,
# alongside plot_auc_summary.py's own auc_summary_report.

import os
import sys
import json
import datetime
import warnings

import numpy as np
import pandas as pd
import matplotlib

matplotlib.use("Agg")  # non-interactive backend
import matplotlib.pyplot as plt

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)
sys.path.insert(0, os.path.dirname(_HERE))
sys.path.insert(0, os.path.join(_HERE, "DeepUnitMatch"))

import run_deepunitmatch_batch_onMerged as base_batch
import plot_auc_summary as auc_summary_mod
import UnitMatchPy.utils as util
from DeepUnitMatch.testing import test as dumtest
from generate_merged_dataset import DUM_NONMERGED_DATAPATH

# ── settings ─────────────────────────────────────────────────────────────────
BASE_INPUT = base_batch.BASE_INPUT
BASE_OUTPUT = base_batch.BASE_OUTPUT
OUTPUT_DIR = os.path.join(BASE_OUTPUT, "auc_vs_delta_days_report")

METADATA_INDEX_PATH = os.path.join(DUM_NONMERGED_DATAPATH, "metadata_index.json")
# Regenerated by build_session_date_lookup() into OUTPUT_DIR on first run (and
# reused on later runs) since redoing the good-unit/RawSpikes-exists check for
# every group is the slow part of this script and its result never changes
# unless the merged tree itself is regenerated.
SESSION_DATE_CACHE_PATH = os.path.join(OUTPUT_DIR, "session_dates_cache.json")

MODELS_TO_INCLUDE = auc_summary_mod.MODELS_TO_INCLUDE

# Bin edges in days between the two sessions of a pair (right-open: [lo, hi)),
# spanning same-day recordings up to ~2 years apart on a roughly log scale --
# tracking studies here span from same-day duplicate recordings out to
# several-hundred-day gaps, so linear bins would leave the long tail empty.
BIN_EDGES = np.array(
    [0, 1, 3, 7, 14, 21, 30, 45, 60, 90, 120, 180, 270, 365, 545, 730, np.inf]
)

# Same sign convention as test.auc_summary_from_functional_scores: metrics
# where *lower* means a better match need negating before the higher-is-better
# AUC calculation below.
NEGATE_FOR_AUC = dumtest.NEGATE_FOR_AUC


# ── session date lookup (reconstructed, not persisted by the pipeline) ─────


def _bin_labels(edges):
    labels = []
    for lo, hi in zip(edges[:-1], edges[1:]):
        labels.append(f"{int(lo)}+" if np.isinf(hi) else f"{int(lo)}-{int(hi)}")
    return labels


BIN_LABELS = _bin_labels(BIN_EDGES)


def build_session_date_lookup(base_input=BASE_INPUT, metadata_index_path=METADATA_INDEX_PATH):
    """
    For every merged-data group, reconstruct {RecSes number -> date}.

    Replicates the same good-unit selection (build_good_units_from_labels)
    and "at least one good unit's RawSpikes.npy actually exists" survival
    check that run_deepunitmatch_batch_onMerged.py's _prepare_session() /
    load_waveforms_for_good_units() use to decide which merged session
    folders get a session_id slot (and therefore a RecSes number) -- without
    loading any waveform data, same as run_emd_batch_onMerged.py's
    stage_group(). A session's numbered folder name equals its 0-based
    position in the original (pre-merge) KS_dirs list (generate_merged_dataset.py
    mirrors every KS_dirs entry, not just the ones with good units), which is
    exactly the indexing generate_metadata_index.py's exp_ids uses -- so
    folder name + 1 == the metadata index's exp_key.

    Returns {dataset_key ("mouse/probe/loc"): {recses (1-based int): date}}.
    """
    if not os.path.isfile(metadata_index_path):
        raise FileNotFoundError(
            f"metadata_index.json not found at {metadata_index_path} -- run "
            "generate_metadata_index.py against the non-merged data root first."
        )
    with open(metadata_index_path) as f:
        metadata_index = json.load(f)

    lookup = {}
    groups = base_batch.find_merged_groups()
    print(f"Reconstructing session dates for {len(groups)} group(s)...")
    for i, merged_dir in enumerate(groups):
        dataset_key = os.path.relpath(os.path.dirname(merged_dir), base_input).replace("\\", "/")
        meta = metadata_index.get(dataset_key)
        if meta is None:
            print(f"  [{i + 1}/{len(groups)}] {dataset_key}: not in metadata_index.json, skipping.")
            continue

        session_names = sorted(
            (d for d in os.listdir(merged_dir) if d.isdigit() and os.path.isdir(os.path.join(merged_dir, d))),
            key=int,
        )
        if not session_names:
            continue

        ks_dirs = [os.path.join(merged_dir, d) for d in session_names]
        try:
            wave_paths, unit_label_paths, _ = util.paths_from_KS(ks_dirs)
        except Exception as e:
            print(f"  [{i + 1}/{len(groups)}] {dataset_key}: paths_from_KS failed ({e}), skipping.")
            continue

        good_units_per_session = base_batch.build_good_units_from_labels(unit_label_paths)

        dates = meta.get("dates", {})
        recses = 0
        mapping = {}
        for folder, wave_path, g_units in zip(session_names, wave_paths, good_units_per_session):
            survives = any(
                os.path.exists(os.path.join(wave_path, f"Unit{int(uid)}_RawSpikes.npy"))
                for uid in g_units.flatten()
            )
            if not survives:
                continue
            recses += 1
            exp_key = str(int(folder) + 1)
            date_str = dates.get(exp_key)
            if date_str:
                mapping[recses] = date_str

        lookup[dataset_key] = mapping
        if (i + 1) % 25 == 0:
            print(f"  ...processed {i + 1}/{len(groups)} groups")

    return lookup


def get_session_date_lookup():
    """Load the cached session-date lookup if present, else build + cache it."""
    if os.path.isfile(SESSION_DATE_CACHE_PATH):
        print(f"Loading cached session-date lookup from {SESSION_DATE_CACHE_PATH}")
        with open(SESSION_DATE_CACHE_PATH) as f:
            raw = json.load(f)
        # JSON keys are always strings; recses needs to be int for lookups.
        return {dataset: {int(k): v for k, v in mapping.items()} for dataset, mapping in raw.items()}

    lookup = build_session_date_lookup()
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    with open(SESSION_DATE_CACHE_PATH, "w") as f:
        json.dump(lookup, f, indent=2)
    print(f"Wrote session-date lookup cache to {SESSION_DATE_CACHE_PATH}")
    return lookup


# ── AUC over a flat (already across-session, already binned) array pair ────


def _auc_from_flat(matches_bool, metric_values):
    """
    Same recall/FPR/trapezoid logic as DeepUnitMatch.testing.test.AUC(), but
    over flat arrays already restricted to across-session pairs (instead of
    an (n_units, n_units) matrix + session_id) -- so it can be reused per
    delta-days bin. Returns NaN when there are no matches or no non-matches
    to rank against (AUC() raises in the same situation).
    """
    P = int(matches_bool.sum())
    N = len(matches_bool) - P
    if P < 1 or N < 1:
        return np.nan
    order = np.argsort(metric_values)[::-1]
    m_sorted = matches_bool[order]
    tp = np.cumsum(m_sorted)
    fp = np.cumsum(~m_sorted)
    recall = tp / P
    fpr = fp / N
    if hasattr(np, "trapezoid"):
        return float(np.trapezoid(recall, fpr))
    return float(np.trapz(recall, fpr))


# ── collect: bin every across-session pair from every dataset/model ────────


def collect_binned_pairs(session_date_lookup, base_output=BASE_OUTPUT, models_to_include=MODELS_TO_INCLUDE):
    """
    Walk base_output for every AUC_summary.json (same discovery as
    plot_auc_summary.collect_auc_summaries), and for each one load its sibling
    MatchTable.csv, restrict to across-session pairs with a resolvable
    delta-days, and accumulate matches/metric values per (model, score, bin)
    and a separate matches/total per (model, bin) for the match-rate curve.

    NaN functional-score entries are dropped per-pair (a simpler approximation
    of test.AUC()'s whole-row masking, appropriate here since we no longer
    have the full per-unit matrix once pairs from many datasets are pooled).

    Returns (score_bins, rate_bins):
      score_bins: {(model, score, bin_label): {"matches": [...], "metric": [...]}}
      rate_bins: {(model, bin_label): {"matches": [...], "total": [...]}}
    (lists of arrays, concatenated by the caller once collection is done).
    """
    score_bins = {}
    rate_bins = {}
    n_found = 0

    for root, dirs, files in os.walk(base_output, topdown=True):
        dirs[:] = [d for d in dirs if not auc_summary_mod._should_skip_dir(d)]
        if "AUC_summary.json" not in files:
            continue
        dirs[:] = []

        model = os.path.basename(root)
        if models_to_include is not None and model not in models_to_include:
            continue

        dataset = os.path.relpath(os.path.dirname(root), base_output).replace("\\", "/")
        date_map = session_date_lookup.get(dataset)
        if not date_map:
            continue

        match_table_path = os.path.join(root, "MatchTable.csv")
        auc_summary_path = os.path.join(root, "AUC_summary.json")
        if not os.path.isfile(match_table_path):
            continue

        with open(auc_summary_path) as f:
            try:
                auc_summary = json.load(f)
            except json.JSONDecodeError:
                continue
        scores = [k for k in auc_summary.keys() if k != "n_matches_across_sessions"]

        header = pd.read_csv(match_table_path, nrows=0).columns
        scores = [s for s in scores if s in header]
        usecols = ["RecSes 1", "RecSes 2", "Matches"] + scores
        df = pd.read_csv(match_table_path, usecols=usecols)

        df["RecSes 1"] = df["RecSes 1"].astype(int)
        df["RecSes 2"] = df["RecSes 2"].astype(int)
        df = df[df["RecSes 1"] != df["RecSes 2"]]

        date1 = df["RecSes 1"].map(date_map)
        date2 = df["RecSes 2"].map(date_map)
        have_dates = date1.notna() & date2.notna()
        if not have_dates.any():
            continue
        df = df[have_dates]
        d1 = pd.to_datetime(date1[have_dates])
        d2 = pd.to_datetime(date2[have_dates])
        delta_days = (d1 - d2).abs().dt.days.to_numpy()

        bin_idx = np.digitize(delta_days, BIN_EDGES) - 1
        bin_idx = np.clip(bin_idx, 0, len(BIN_LABELS) - 1)

        matches_bool = df["Matches"].to_numpy().astype(bool)

        for b in np.unique(bin_idx):
            mask = bin_idx == b
            label = BIN_LABELS[b]
            key = (model, label)
            entry = rate_bins.setdefault(key, {"matches": [], "total": []})
            entry["matches"].append(int(matches_bool[mask].sum()))
            entry["total"].append(int(mask.sum()))

        for score in scores:
            signed = -df[score].to_numpy() if score in NEGATE_FOR_AUC else df[score].to_numpy()
            valid = np.isfinite(signed)
            for b in np.unique(bin_idx[valid]):
                mask = valid & (bin_idx == b)
                if not mask.any():
                    continue
                key = (model, score, BIN_LABELS[b])
                entry = score_bins.setdefault(key, {"matches": [], "metric": []})
                entry["matches"].append(matches_bool[mask])
                entry["metric"].append(signed[mask])

        n_found += 1
        if n_found % 25 == 0:
            print(f"  ...processed {n_found} MatchTable.csv files so far", flush=True)

    if n_found == 0:
        raise RuntimeError(f"No usable (AUC_summary.json, MatchTable.csv, session dates) found under {base_output}")
    print(f"Processed {n_found} dataset/model MatchTable.csv files.")
    return score_bins, rate_bins


# ── reduce to per-bin numbers + plot ────────────────────────────────────────


def summarise_auc(score_bins):
    rows = []
    for (model, score, label), entry in score_bins.items():
        matches = np.concatenate(entry["matches"])
        metric = np.concatenate(entry["metric"])
        rows.append(
            {
                "model": model,
                "score": score,
                "bin": label,
                "n_pairs": len(matches),
                "n_matches": int(matches.sum()),
                "auc": _auc_from_flat(matches, metric),
            }
        )
    return pd.DataFrame(rows)


def summarise_match_rate(rate_bins):
    rows = []
    for (model, label), entry in rate_bins.items():
        total = sum(entry["total"])
        matches = sum(entry["matches"])
        rows.append(
            {
                "model": model,
                "bin": label,
                "n_pairs": total,
                "n_matches": matches,
                "match_rate": matches / total if total else np.nan,
            }
        )
    return pd.DataFrame(rows)


def _bin_order(labels):
    return sorted(labels, key=lambda l: BIN_LABELS.index(l))


def plot_vs_delta_days(df, value_col, ylabel, title, out_path, min_pairs=20):
    """
    One line per model, x = delta-days bin (in BIN_LABELS order), y = value_col.
    Bins with fewer than min_pairs underlying pairs are dropped (too noisy to
    be meaningful) rather than plotted.
    """
    sub = df[df["n_pairs"] >= min_pairs].dropna(subset=[value_col])
    if sub.empty:
        return None

    models = sorted(sub["model"].unique())
    bins_present = _bin_order(sub["bin"].unique())
    x_pos = {b: i for i, b in enumerate(bins_present)}

    fig, ax = plt.subplots(figsize=(max(7, 0.6 * len(bins_present)), 5))
    cmap = plt.get_cmap("tab10")
    for i, model in enumerate(models):
        model_sub = sub[sub["model"] == model].copy()
        model_sub["x"] = model_sub["bin"].map(x_pos)
        model_sub = model_sub.sort_values("x")
        ax.plot(
            model_sub["x"], model_sub[value_col], marker="o", label=model,
            color=cmap(i % cmap.N), linewidth=1.5, markersize=5,
        )

    ax.set_xticks(range(len(bins_present)))
    ax.set_xticklabels(bins_present, rotation=45, ha="right")
    ax.set_xlabel("delta-days between sessions")
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.grid(alpha=0.3)
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    return out_path


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    session_date_lookup = get_session_date_lookup()
    n_datasets_with_dates = sum(1 for m in session_date_lookup.values() if m)
    print(f"Have session dates for {n_datasets_with_dates}/{len(session_date_lookup)} dataset(s).\n")

    score_bins, rate_bins = collect_binned_pairs(session_date_lookup)

    auc_df = summarise_auc(score_bins)
    auc_csv = os.path.join(OUTPUT_DIR, "auc_vs_delta_days.csv")
    auc_df.to_csv(auc_csv, index=False)
    print(f"Wrote {auc_csv}")

    rate_df = summarise_match_rate(rate_bins)
    rate_csv = os.path.join(OUTPUT_DIR, "match_rate_vs_delta_days.csv")
    rate_df.to_csv(rate_csv, index=False)
    print(f"Wrote {rate_csv}")

    for score in sorted(auc_df["score"].unique()):
        out_path = os.path.join(OUTPUT_DIR, f"auc_vs_delta_days_{score}.png")
        result = plot_vs_delta_days(
            auc_df[auc_df["score"] == score], "auc", f"AUC ({score})",
            f"AUC vs delta-days: {score}", out_path,
        )
        if result:
            print(f"  Plotted {score} -> {result}")

    rate_out_path = os.path.join(OUTPUT_DIR, "match_rate_vs_delta_days.png")
    result = plot_vs_delta_days(
        rate_df, "match_rate", "matched fraction of across-session pairs",
        "Match rate vs delta-days", rate_out_path,
    )
    if result:
        print(f"  Plotted match rate -> {result}")


if __name__ == "__main__":
    main()
