%bc_getQualityUnitType

if BCparam.computeDistanceMetrics && ~isnan(BCparam.isoDmin)
    unitType = nan(length(qMetric.percSpikesMissing), 1);
    unitType(qMetric.nPeaks > BCparam.maxNPeaks | qMetric.nTroughs > BCparam.maxNTroughs | qMetric.somatic ~= BCparam.somatic ...
        | qMetric.spatialDecaySlope <=  BCparam.minSpatialDecaySlope | qMetric.waveformDuration < BCparam.minWvDuration |...
        qMetric.waveformDuration > BCparam.maxWvDuration | qMetric.waveformBaseline >= BCparam.maxWvBaselineFraction) = 0; % NOISE or NON-SOMATIC
    unitType(any(qMetric.percSpikesMissing <= BCparam.maxPercSpikesMissing, 2)' & qMetric.nSpikes > BCparam.minNumSpikes & ...
        any(qMetric.Fp <= BCparam.maxRPVviolations, 2)' & ...
        qMetric.rawAmplitude > BCparam.minAmplitude & qMetric.isoDmin >= BCparam.isoDmin & isnan(unitType)) = 1; % SINGLE SEXY UNIT
    unitType(isnan(unitType)) = 2; % MULTI UNIT

else
    unitType = nan(length(qMetric.percSpikesMissing), 1);
    unitType(qMetric.nPeaks > BCparam.maxNPeaks | qMetric.nTroughs > BCparam.maxNTroughs | qMetric.somatic ~= BCparam.somatic ...
        | qMetric.spatialDecaySlope <=  BCparam.minSpatialDecaySlope | qMetric.waveformDuration < BCparam.minWvDuration |...
        qMetric.waveformDuration > BCparam.maxWvDuration  | qMetric.waveformBaseline >= BCparam.maxWvBaselineFraction) = 0; % NOISE or NON-SOMATIC
    unitType(any(qMetric.percSpikesMissing <= BCparam.maxPercSpikesMissing, 2)' & qMetric.nSpikes > BCparam.minNumSpikes & ...
        any(qMetric.Fp <= BCparam.maxRPVviolations, 2)' & ...
        qMetric.rawAmplitude > BCparam.minAmplitude & isnan(unitType)') = 1; % SINGLE SEXY UNIT
    unitType(isnan(unitType)') = 2; % MULTI UNIT

end
